### ISSUE TITLE
how do I use modtweaker!?

### ISSUE THREAD

**Issue by lShanghaiMoonl** [jaredlll08/ModTweaker#345]
I have the files now what, do I install it into my mods folder do I run it? I have no idea what to actually do with the file. I wish it told you what to do if you havn't used this mod before....

**Comment by Lanse505** [comment]
@lShanghaiMoonl 
Look if you don't know how to install the mod to begin with you probably shouldn't be tinkering with either minetweaker/crafttweaker and Modtweaker.

Also there are perfectly functional guides linked through the minetweaker wiki which you can find on both modtweakers, minetweakers and crafttweakers Curseforge page >->. If you for some reason didn't get the mod through Curse/Curseforge give @jaredlll08 a link so he can send that site a CnD. 

Finally no offence but:
This is what you should have written;

"Excuse me, but I was wondering if I could get some help.
I've downloaded the files for Modtweaker (& Minetweaker/Crafttweaker) and I'm currently wondering how I install the mod itself? 

Aswell as I'm wondering if there are any "instructions" or "guides" how to use this mod since it doesn't come with a guide bundled with the mod itself.

I'm sorry for inconveniencing you with this question.
Great mod btw :)"

**Comment by samuelroy21** [comment]
harsh.

**Comment by Lanse505** [comment]
@samuelroy21 
Harsh but fair :P

**Comment by Lanse505** [comment]
@lShanghaiMoonl 
Follow-up Question:
Do you have forge installed in your client?

Also; 
Are you using the Curse Launcher for this in which case....
Why did you ask about where to install the files?

**Comment by Yulife** [comment]
You mean the zs files? They go into the "scripts" folder in your minecraft directory after you installed Minetweaker and Modtweaker. Once you have both running, drop the zs files into the script folder and run the game.
