### ISSUE TITLE
Tinkers Construct Mod Null-1.10.2

### ISSUE THREAD

**Issue by WenXin20** [jaredlll08/ModTweaker#347]
Modtweaker 2.0.0
Forge 2073
Mantle 0.10.4
Tinkers 2.4.0
I tried adding recipes for the drying rack and the smeltery, following the guidelines on the wiki, but I just get a null back when I reload minetweaker.
This is what I put in: 
#Drying Rack
#InputStack, OutputStack, Time in Ticks
mods.tconstruct.Drying.addRecipe(<minecraft:tallgrass:1>, <minecraft:deadbush>, 50);
#Smeltery
#InputStack, OutputFluid, TemperatureAmount, BlockRender
mods.tconstruct.Smeltery.addMelting(<minecraft:porkchop>, <liquid:water> * 200, 200, <minecraft:porkchop>);

**Comment by jaredlll08** [comment]
First of all, DON'T RELOAD.
Second of all, try modtweaker 2.0.1 :)

**Comment by WenXin20** [comment]
Ok

**Comment by jaredlll08** [comment]
Did it work without reloading?

**Comment by WenXin20** [comment]
No

**Comment by utoc** [comment]
Also having trouble with TiCo and MT 2.0.1

````mods.tconstruct.Casting.removeTableRecipe(<tconstruct:cast_custom:3>);````

Gives console error ````ERROR: Error executing tconstruct.zs: slimeknights.tconstruct.library.smeltery.BucketCastingRecipe cannot be cast to slimeknights.tconstruct.library.smeltery.CastingRecipe````

Paste from crafttweaker log: http://pastebin.com/fSF1QD1Z

````mods.tconstruct.Casting.addTableRecipe(<tconstruct:cast_custom:3>, <liquid:gold> * 576);````

Gives console error: ````ERROR: Error executing tconstruct.zs: com.google.common.collect.RegularImmutableList cannot be cast to java.util.LinkedList````

Paste from crafttweaker log: http://pastebin.com/VjTYcnuA

**Comment by jaredlll08** [comment]
@tommyTT any idea if your PR fixed this??

**Comment by tommyTT** [comment]
The ClassCastException for BucketCastingRecipe is fixed by my PR. The CCE for the RegularImmutableList didn't occur for me but can be easily avoided, LinkedList is not required for the Add class, a normal List is sufficient. I think that was a problem in 2.0.1 before you got access to the TinkersRegistry via reflection, because the getAllTableCastingRecipes() returned an immutable list.

**Comment by jaredlll08** [comment]
Well I just looked at the code my side, and didn't see anything at the line
the crash gave

**Comment by tommyTT** [comment]
In the current code base, the lines would be 105 for the BucketCastingRecipe Exception, but my PR introduced the instanceof check in 104 which prevents that.
The ImmutableList Exception can occur in lines 44 or 62 but won't anymore, because you get the reference to the lists via reflection now. It would be safer to remove those casts altogether and use List instead, so Tinkers can change their used List implementation without your code being affected.

**Comment by jaredlll08** [comment]
ok cool, will make the change and close this

**Comment by jaredlll08** [comment]
Ok so, I'm going to leave it as a linked list, since if people start complaining about it being wrong, then it means I need to update tinkers anyway xD
