### ISSUE TITLE
[Suggestion] IC2Classic support for 1.10.2

### ISSUE THREAD

**Issue by Speiger** [jaredlll08/ModTweaker#429]
Well IC2C is almost at its release. (We just wait on wiki doc and just some testing)
And i kinda wanted suggest it for a support.

The API is public and i can provide you with a Closed Beta version.

API is from my side finalized.

**Comment by tjsd** [comment]
Hope this gets added :)

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore

**Comment by Speiger** [comment]
@jaredlll08 well thanks. I asked this months ago.... And there was no answer no response... Now no support. Very nice.

**Comment by jaredlll08** [comment]
I would just like to remind you that you said that you would give me an api to implement the support with, and said that the mod would be released about 3-4 months before this issue was even created. It is not my fault that you finished your 1.10.2 version after 1.11.2 had been released.

http://i.blamejared.com/MJvCL.png

**Comment by Speiger** [comment]
oh well. Luckly the Exp support works on classic...
