### ISSUE TITLE
[1.10.2] Tinkers casting.remove doesn't work on server but works in single-player.

### ISSUE THREAD

**Issue by Claycorp** [jaredlll08/ModTweaker#485]
#### Issue Description:
I removed sharpening kits with ```mods.tconstruct.Casting.removeTableRecipe(<tconstruct:sharpening_kit:*>, null, null);```
and this works fine in single-player but if you try to load the same script on a server it errors.
#### What happens:
Error is thrown. https://pastebin.com/EFnP2HCB

#### What you expected to happen:
It to work fine.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Full scrip file for sanity's sake: https://pastebin.com/yHnRQkVX

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
Full server log: https://pastebin.com/pY7NaaMJ
Full client log: https://pastebin.com/QFSjtuSj

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 2297
- Crafttweaker: 3.0.25
- ModTweaker: 2.0.12
- MTLib: 1.0.2
- Tinkers Construct: 2.6.3
- Mantle 1.1.5

**Comment by PCSpinner** [comment]
I'm experiencing the same problem, tho with more recent versions of MTLib (1.0.3) and Tinkers Construct (2.6.5). 
To add to the description of the problem: unlike most errors, instead of just skipping that line and loading the rest of the file, it results in
**ERROR: Error executing filename.zs: null**
causing the entire file to not load, tho other files still load fine.

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore / Issue has been fixed in 1.12
