### ISSUE TITLE
Adding TE Pulverizer recipes does nothing

### ISSUE THREAD

**Issue by Syndaryl** [jaredlll08/ModTweaker#523]
#### Issue Description:
I thought I'd submitted this issue yesterday but I can't see it anywhere. Appologies if this is a duplicate.
I have several recipes added to the Thermal Expansion Pulverizer, but none of them are actually added. My scripts pass /ct parse.

#### What happens:
No error messages, no new recipes. 

#### What you expected to happen:
Either the new recipes to appear, or an error message of some sort.

#### Script used:
https://gist.github.com/Syndaryl/7bf0ed22ed2f4bcdb0a674cc688e26d4

#### Minetweaker.log file:
https://gist.github.com/Syndaryl/8902f449084186c6b9ad3f71c1560cac

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.1
- Forge: 14.22.0.2467 
- Crafttweaker: CraftTweaker2-1.12-4.0.4
- ModTweaker: modtweaker-4.0.1.jar
- MTLib: MTLib-3.0.0.jar

#### Your most recent log file where the issue was present: 
https://gist.github.com/Syndaryl/a67971c1255c7f5c5afd4bad2eb45b57

**Comment by jaredlll08** [comment]
Uh, what do you mean by /ct parse?

On Sep 6, 2017 16:29, "Syndaryl" <notifications@github.com> wrote:

Issue Description:

I thought I'd submitted this issue yesterday but I can't see it anywhere.
Appologies if this is a duplicate.
I have several recipes added to the Thermal Expansion Pulverizer, but none
of them are actually added. My scripts pass /ct parse.
What happens:

No error messages, no new recipes.
What you expected to happen:

Either the new recipes to appear, or an error message of some sort.
Script used:

https://gist.github.com/Syndaryl/7bf0ed22ed2f4bcdb0a674cc688e26d4
Minetweaker.log file:

https://gist.github.com/Syndaryl/8902f449084186c6b9ad3f71c1560cac
------------------------------
Affected Versions (Do *not* use "latest"):

   - Minecraft: 1.12.1
   - Forge: 14.22.0.2467
   - Crafttweaker: CraftTweaker2-1.12-4.0.4
   - ModTweaker: modtweaker-4.0.1.jar
   - MTLib: MTLib-3.0.0.jar

Your most recent log file where the issue was present:

https://gist.github.com/Syndaryl/a67971c1255c7f5c5afd4bad2eb45b57

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jaredlll08/ModTweaker/issues/523>, or mute the thread

**Comment by Syndaryl** [comment]
/CT Syntax 
Sorry. I make that brain fart every time I try to use it. For some reason I keep thinking of it as "run my code past the parser" rather than "get my syntax checked".

**Comment by Boolyman** [comment]
I guess my issue would be considered a duplicate on 1.12.2, but with the Fluid Transposer, not the Pulverizer.  I use the Syntax provided on the mod tweaker wiki, and I get a "No member found" error when the game loads.  I tried seeking help from the COFH group, but was... less than successful.

My syntax is as follows:

mods.thermalexpansion.Transposer.addFillRecipe(2000, <biomesoplenty:log_4:5> * 2, <minecraft:log>, <liquid:water> * 200);

**Comment by kindlich** [comment]
@Boolyman Your issue is in not related :smile: 
There is no TE Transposer support in 1.12 as of now!

You can check the available TE handlers here
http://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/ThermalExpansion/Crucible/

**Comment by jaredlll08** [comment]
@Syndaryl the issue is that you are trying to register recipes that use inputs that are already used, so you'll notice that the flint and steel recipe works fine (provided you are running vanilla TE with no other mods, that was my test environment), but something such as:
```
mods.thermalexpansion.Pulverizer.addRecipe(<minecraft:stone_slab:0>, <minecraft:cobblestone>*2, 1500, <minecraft:sand>*1, 25);
```
doesn't work since cobblestone is used in other recipes.

Also a lot of your recipes use the same input... which just won't work
