### ISSUE TITLE
[1.12.2] TiC fuel temperature not working (always 300°)

### ISSUE THREAD

**Issue by Thyriel** [jaredlll08/ModTweaker#547]
#### Issue Description:
Adding a tinker fuel with a set temperature adds the fuel with 300° temperature instead the set one.
Ingame hovering over the fuel bar in the TiC UI shows 300°. When adding something to smelt (e.g. Ice Block which requires 301°) the shown temperature drops to zero. (sometimes also happens when adding something that smelts at 300°. Sometimes it's smelting the item, sometimes not. Also i noticed that with an added fuel the temperature of the lava fuel drops to 1000° from 1300° too)
Neither higher nor lower temp then lava works.

#### What you expected to happen:
Fuel being added with the set temperature

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/87P4fVUZ

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/5qG3mGEN

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2517
- Crafttweaker:  4.0.8
- ModTweaker: 4.0.4
- MTLib: 3.0.1

**Comment by jaredlll08** [comment]
Seriously. Search before making an issue.
https://github.com/jaredlll08/ModTweaker/issues/546#issuecomment-340178342

**Comment by Thyriel** [comment]
Seriously. Write your [documentation](http://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/TConstruct/Fuel/) correctly if you don't want multiple issues about the same thing...

**Comment by jaredlll08** [comment]
I would just like to remind you that what I am not paid to mod. The person who does my documentation is not paid to do so. What we do is a hobby, and we do it in OUR free time. We have no obligation to even host documentation for the mod.

The first time we were alerted about this was 7 hours ago. It hasn't even been a day since we have been alerted of this issue,its not like we have known about for days or weeks. 7 hours. Of those 7 hours, 4 of them I have been sleeping and the other 3 I have been dealing with real life stuff, so I havnt exactly had the time to update the wiki. 

Lastly, the very first paragraph of the issue template, which, considering you followed it, you must have read, tells you to look for similar issues incase you are making a duplicate. You wouldn't even have needed to use the search bar, that other issue is the last issue that we closed, so it is at the top of the closed issues list. 

So seriously. Search before making an issue.
