### ISSUE TITLE
Lower case arguments vs Upper case check

### ISSUE THREAD

**Issue by Shovinus** [jaredlll08/ModTweaker#569]
https://github.com/jaredlll08/ModTweaker/blob/65ef2d3d7200aa3772c978f25174568893e29531/src/main/java/modtweaker/mods/botania/commands/BotaniaLogger.java#L32

You seem to lowercase the arguments but not the validation, thus it never matches

**Comment by Morpheus1101** [comment]
I believe this maybe the cause of the issue im having with 1 botania item..

/ct hand tells me: `<botania:manatablet>.withTag({mana: 500000, creative: 1 as byte})` and as such adds the recipe, but that item in botania technically dosent exist

But when checking botania code its actually `<botania:manaTablet>.withTag({mana: 500000, creative: 1 as byte})`

**Comment by p455w0rd** [comment]
yeah..this is the correct standard..but then you have Vazkii doing this: https://github.com/Vazkii/Botania/blob/938aab69e5c46d782af3fdb9d647ccd754651853/src/main/java/vazkii/botania/common/lib/LibItemNames.java#L24 ..soo..remove the enforcement of lower case since Forge isn't enforcing in registry names pls? morph and i were discussing..i didn't know he was posting lol

**Comment by Shovinus** [comment]
Thank you Jared :*
