### ISSUE TITLE
Thermal Expansion Augmentations

### ISSUE THREAD

**Issue by ghost** [jaredlll08/ModTweaker#744]
Can you add support to augmentations? For exmaple: Flux Anodizers and Pyro Concentrator

Thanks in advance!

PM.: Love your tweakers! Keep it up! <3

**Comment by jaredlll08** [comment]
None of those augments are configurable, each just apply a hardcoded (maybe changeable via config), multiplier to ore processing.

A while back we did go through and add support for all augments that supported them, so unless COFH added more augments since then, all the augments that can be configurable are configurable.

**Comment by ghost** [comment]
Thanks for the fast response! Just why i ask is because i didn't saw the commands at the documentation.

Edit: I'm an idiot. If i remove the recipe in a machinery it automatically removes the augment recipe also.
