### ISSUE TITLE
Thermal Foundation Induction Smelter

### ISSUE THREAD

**Issue by ghost** [jaredlll08/ModTweaker#745]
#### Issue Description:
(It's a repost from CraftTweaker repo) I tried to remove some tool/armor/horse armor recipes from the Induction Smelter.

#### What happens:
The recipes won't delete.

#### What you expected to happen:
Delete the recipes.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): [crafttweaker.log](https://pastebin.com/14zam3J3)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: **1.12.2**
- Forge: **forge-14.23.5.2847**
- Crafttweaker: **CraftTweaker2-1.12-4.1.20**
- ModTweaker: **modtweaker-4.0.17**
- MTLib: **MTLib-3.0.6**

#### Your most recent log file where the issue was present: 

[latest.log](https://pastebin.com/JxWMVUXK)

**Comment by jaredlll08** [comment]
we are passing the values to TE just fine, so it must be on their end, especially because it says that the recipe still exists after we removed it.
https://github.com/jaredlll08/ModTweaker/blob/be734c533d1f2a647b1f916c5ac8b4066d50664e/src/main/java/com/blamejared/compat/thermalexpansion/InductionSmelter.java#L82
this line can only trigger if the removal failed on TE's side.

**Comment by neOVER9000** [comment]
i have the same problem is there a solution?
