### ISSUE TITLE
Thermal Expansion questions

### ISSUE THREAD

**Issue by ChromaPIE** [jaredlll08/ModTweaker#771]
#### Issue Description:

- For now every Thermal Expansion machines' input only support IItemStack, it makes no sense. Should also support IOreDictEntry.
- How can I remove all recipes of specific TE machine?
- The log said "No xxx recipe exists for xxx" but it's actually there.
![image](https://user-images.githubusercontent.com/56111366/100701462-b5bece80-33da-11eb-88c1-78e55819502e.png)
![image](https://user-images.githubusercontent.com/56111366/100701497-c3745400-33da-11eb-9dfd-28c5d83df69e.png)
![image](https://user-images.githubusercontent.com/56111366/100701553-dab34180-33da-11eb-9cdc-f7682a31bd58.png)

**Comment by kindlich** [comment]
- The reason our handlers only accept IItemStack is because TE itself only accepts ItemStacks, nothing we can do. They internally handle oredicts based on the item you provide.
- There is no way to remove all recipes from the machines
- Check that you used the correct remove method, the compactor has more than one mode, and the recipes in the screenshot look like "PLATE" recipes, not "ALL"

**Comment by ChromaPIE** [comment]
> * The reason our handlers only accept IItemStack is because TE itself only accepts ItemStacks, nothing we can do. They internally handle oredicts based on the item you provide.
> * There is no way to remove all recipes from the machines
> * Check that you used the correct remove method, the compactor has more than one mode, and the recipes in the screenshot look like "PLATE" recipes, not "ALL"

Alright. Also the problem with recipe removing has been solved. appreciate that!
